# Generated by Django 4.2.11 on 2024-04-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationAPI', '0006_alter_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
