# Generated by Django 4.2.11 on 2024-04-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationAPI', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
