# Generated by Django 4.2.11 on 2024-04-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationAPI', '0010_remove_application_city_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
