# Generated by Django 4.2.11 on 2024-04-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationAPI', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tags',
            field=models.ManyToManyField(blank=True, to='AuthorizationAPI.tag'),
        ),
    ]
