# Generated by Django 4.2.11 on 2024-04-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationAPI', '0013_alter_application_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
