# Generated by Django 4.2.11 on 2024-04-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationAPI', '0014_application_city_application_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
