# Generated by Django 4.2.11 on 2024-04-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorizationAPI', '0015_alter_application_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='urgent',
            field=models.CharField(default='all', max_length=15),
        ),
    ]
