/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GatheringImport } from './routes/gathering'
import { Route as CabinetImport } from './routes/cabinet'
import { Route as IndexImport } from './routes/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as ApplicationsSearchImport } from './routes/applications/search'
import { Route as ApplicationsCreateImport } from './routes/applications/create'
import { Route as ApplicationsIdImport } from './routes/applications/$id'

// Create/Update Routes

const GatheringRoute = GatheringImport.update({
  path: '/gathering',
  getParentRoute: () => rootRoute,
} as any)

const CabinetRoute = CabinetImport.update({
  path: '/cabinet',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationsSearchRoute = ApplicationsSearchImport.update({
  path: '/applications/search',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationsCreateRoute = ApplicationsCreateImport.update({
  path: '/applications/create',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationsIdRoute = ApplicationsIdImport.update({
  path: '/applications/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cabinet': {
      preLoaderRoute: typeof CabinetImport
      parentRoute: typeof rootRoute
    }
    '/gathering': {
      preLoaderRoute: typeof GatheringImport
      parentRoute: typeof rootRoute
    }
    '/applications/$id': {
      preLoaderRoute: typeof ApplicationsIdImport
      parentRoute: typeof rootRoute
    }
    '/applications/create': {
      preLoaderRoute: typeof ApplicationsCreateImport
      parentRoute: typeof rootRoute
    }
    '/applications/search': {
      preLoaderRoute: typeof ApplicationsSearchImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CabinetRoute,
  GatheringRoute,
  ApplicationsIdRoute,
  ApplicationsCreateRoute,
  ApplicationsSearchRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
])

/* prettier-ignore-end */
